[project]
authors = []
channels = ["conda-forge","robostack-staging"]
description = "Add a short description here"
name = "error-reproducer"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = {cmd="colcon build --symlink-install --cmake-args -DPython_FIND_VIRTUALENV=ONLY -DPython3_FIND_VIRTUALENV=ONLY" }

[dependencies]

python = ">=3.11,<3.12"

# Build Tools
cmake = ">=3.30.2,<4.0"
pkg-config = ">=0.29.2,<0.30.0"
make = ">=4.3,<5.0"
ninja = ">=1.12.1,<2.0"
colcon-common-extensions = ">=0.3.0,<0.4.0"
catkin_tools = "*"
gxx = ">=13.3.0,<14.0"

# BehaviorTree.CPP
zeromq = ">=4.3.4"
gtest = ">=1.14.0,<1.15"
gmock = ">=1.14.0,<1.15"
sqlite = ">=3.40.0,<3.46"

# BehaviorTree.ROS2
boost = "*"
ros-humble-ament-cmake = ">=1.3.7,<2.0"
ros-humble-std-msgs = ">=4.2.3,<5.0"
ros-humble-std-srvs = ">=4.2.3,<5.0"
ros-humble-rclcpp = ">=16.0.8,<17.0"
ros-humble-rclcpp-action = ">=16.0.8,<17.0"
ros-humble-generate-parameter-library = ">=0.3.7,<0.4.0"
ros-humble-rosidl-default-generators = ">=1.2.0,<2.0"
ros-humble-rosidl-default-runtime = ">=1.2.0,<2.0"
ros-humble-action-msgs = ">=1.2.1,<2.0"

